- name: Criando o banco de dados
  mysql_db:
    name: "wp_db_prd"
    state: present
  when: ansible_facts['distribution'] == "CentOS"
  
- name: Criando o usuario do banco de dados
  mysql_user:
    name: "wp_user_01"
    password: "{{ dbpass }}"
    priv: 'wp_db_prod.*:ALL, GRANT'
    host: "%"
    state: present
  when: ansible_facts['distribution'] == "CentOS"