- name: Create a new database with name 'wp'
  mysql_db:
    name: wpprd
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: wp
    password: "{{ dbpass }}"
    priv: 'wpprd.*:ALL,GRANT'
    host: "%"
    state: present
  when: ansible_facts['distribution'] == "CentOS"