#configuração de bvanco de dados 
- name: criando o banco de dados 'wp_prd'
  mysql_db:
    name: wp_db_prd
    state: present

- name: Criando o usuario do banco de dados 'wp_prd'
  mysql_user:
    name: wp_user_01
    password: "{{ dbpass }}"
    priv: 'wp_db_prod.*:ALL, GRANT'
    host: "%"
    state: present

