# Instalação do mysql server
- name: Instalando pacotes do MariaDB
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb
    - Mysql-python
  when: ansible_facts['distribution'] == "CentOS"

- name: Enable serice mysql, and touch the state
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == "CentOS"
    