# Instalação do mysql server
- name: Instalando pacotes do MariaDB
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb-main
    - Mysql-python
    - perl-DBI
    - libaio
    - libsepol
    - lsof
    - boost-program-options

  when: ansible_facts['distribution'] == "CentOS"

- name: Enable serice mysql, and touch the state
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_facts['distribution'] == "CentOS"
    