- name: install Python e python-pip
  apt:
    pkg:
    - python
    - python-pip
    update_cache: yes
    state:
    presentwhen: (ansible_os_family == "Debian") or (ansible_os_family == "Ubuntu")
  
- name: Removendo Zabbix-Agent
  apt: 
    name: zabbix-agent
    state: removed

- name: Registro de sistema operacional
  shell: lsb_release -si | tr 'A-Z' 'a-z'
  register: SO

- name: Registro da versao do sistema operacional
  shell: lsb_release -sc
  register: SOVERSION
 
- name: Registro do nome da maquina 
  shell: hostname
  register: hname

- name: Registro de IP
  shell: 
  hostname -I | awk '{print $1}'register: hip

- name: Registro de pacote instalado
  shell: dpkg -l | grep zabbix-agent; echo $?
  register: ipack

- name: Removendo bibliotecas Zabbix-Agent
  action: raw dpkg --purge zabbix-release && dpkg --purge zabbix-agent
  when: ipack.stdout != "1"


- name: Baixando biblioteca Zabbix-Agent 5.0
  action: raw wget https://repo.zabbix.com/zabbix/5.0/"{{ SO.stdout }}"/pool/main/z/zabbix-release_5.0.17%2B"{{ SOVERSION.stdout }}"_all.deb
  
- name: Executando novos repositorios .deb
  action: raw dpkg -i zabbix-release_5.0-17+"{{ SOVERSION.stdout }}"_all.deb


- name: Atualizando repositorios
  action: raw apt-get update

- name: Install agent-zabbix
  apt:
    name: zabbix-agent
    state: installed
       
- name: Copiando arquivo de configuracao do zabbix-agent
  copy:
    src: zabbix/zabbix_agentd.conf
    dest: /etc/zabbix/

- name: adicionado nome do host
  action: raw sed -i "s/Hostname=zabbix/Hostname="{{ hname.stdout }}"/g" /etc/zabbix/zabbix_agentd.conf

- name: Iniciar agente zabbix
  service:
    name: zabbix-agent
    state: started
    enabled: yes
- name: enviando arquivo zabbix pip
  copy: 
    src: files/zabbix-api-0.5.4.tar.gz
    dest: /tmp/    
 
- name: instalando o zabbix-api
  shell: pip install /tmp/zabbix-api-0.5.4.tar.gz

- name: Colocando a maquina no monitoramento
  local_action:
    module: zabbix_host
    server_url: "http://10.30.0.27/zabbix/index.php"
    login_user: "Admin"
    login_password: "zabbix"
    host_name: '{{ hname.stdout }}'
    visible_name: '{{ hname.stdout }}'
    description: Instalacao e configuracao via ansible
    host_groups:
      - Linux servers
    link_templates:
      - Template OS Linux
    status: enabled
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: '{{ hip.stdout }}'
        dns: ""
        port: 10050

- name: Restart agente zabbix
  service:
    name: zabbix-agent
    state: restarted
    enabled: yes